services:
  vidispine:
    image: vidispine
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile.vidispine
    volumes:
      - ./vidispine-config.yaml:/etc/vidispine/server.yaml
      - ./vidispine-init.sh:/etc/vidispine/init.sh
    depends_on:
      - postgres
    command: /etc/vidispine/init.sh
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=vidispine
      - POSTGRES_PASSWORD=vidispine
      - POSTGRES_DB=vidispine
