broker:
  user: admin
  password: adminactivemq
  url: tcp://activemq:61616
database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/vidispine
  user: vidispine
  password: vidispine